title:string=Color, font, logo and border defaults

backgroundColor:string=#484848
fontColor:string=#9da097
fontFamily:string=Arial, Helvetica, Geneva, Swiss, SunSans-Regular, sans-serif
fontBaseSize:string=90%
headingFontFamily:string=Arial, Helvetica, Geneva, Swiss, SunSans-Regular, sans-serif

linkColor:string=#e6eadd
linkHoverColor:string=#f28c18

fontSmallSize:string=90%


topbarBackgroundColor:string=#000
breadcrumbsBackground:string=#484848

tabsBorderColor:string=#202020
tabsBorderWidth:string=2px
tabsBottomBorderSelectedWidth:string=3px
tabsFontColor:string=#e6eadd
tabsBackgroundColor:string=#484848
selectedTabBackgroundColor:string=#484848

descriptionColor:string=#9da097

inputFontColor:string=#000

evenRowBackgroundColor:string=#202020
oddRowBackgroundColor:string=#484848
highLightColor:string=#f28c18

messageBackgroundColor:string=#484848
messageBorderColor:string=#484848

weekTableFontHeight:int=10
weekTableGridStep:int=10
todayBackgroundColor:string=#f0f0f0
calGridBorderColor:string=#ccc
calHalfGridBorderColor:string=#e5e5e5

contentBackgroundColor:string=#484848

configFontColor:string=#fff
configBackgroundColor:string=#3e3e3e

portfolioSlideBackgroundColor:string=#f2f2f2

memberActionsBoxBackground:string=#484848
footerBackgroundColor:string=#707070
outlineColor:string=#F28C18
bylineBackgroundColor:string=#202020
messageFontColor:string=#F28C18
listingHeaderBackgroundColor:string=#000
listingHeaderFontColor:string=#ddd
listingBarBorderColor:string=#202020
newsTitleBorderColor:string=#ddd
boxesBorderColor:string=#ddd
specialLinkColor:string=#e6eadd
specialLinkHoverColor:string=#f28c18
bulletColor:string=#ef8e32
boxeHeaderBackgroundColor:string=#484848

twoColumnFormFontColor:string=#fff
twoColumnFormBackground:string=#3A3A3A
