export const base_properties =
{
  "sitePanelLinkColor": "#a7d3ff", 
  "tabsFontColor": "#369", 
  "boxesBorderColor": "#ddd", 
  "sitePanelLinkHoverColor": "#f1f8ff", 
  "bulletColor": "#369", 
  "weekTableGridStep": 10, 
  "borderRadius": 7, 
  "listingHeaderFontColor": "#000", 
  "portfolioSlideBackgroundColor": "#f2f2f2", 
  "tabsBorderColor": "#ff9c00", 
  "fontFamily": "Helvetica, sans-serif", 
  "inputFontColor": "#000", 
  "configFontColor": "#000", 
  "configBackgroundColor": "#f0f0f0", 
  "inputSubmitColor": "#000", 
  "calHalfGridBorderColor": "#e5e5e5", 
  "fontColor": "#000", 
  "tabsBorderWidth": "2px", 
  "breadcrumbsBackground": "rgba(255,255,255,0.85)", 
  "selectedTabBackgroundColor": "#fff", 
  "fontMenuSize": "16px", 
  "title": "Color, font, logo and border defaults", 
  "topbarBackgroundColor": "#fff", 
  "tabsBackgroundColor": "#fff", 
  "articleWrapperBackground": "transparent", 
  "listingBarBorderColor": "#ddd", 
  "bylineBackgroundColor": "#fff", 
  "linkColor": "#369", 
  "boxeHeaderBackgroundColor": "#ddd", 
  "backgroundColor": "#fff", 
  "messageBackgroundColor": "#fff", 
  "footerBackgroundColor": "#000", 
  "descriptionColor": "#333", 
  "todayBackgroundColor": "#f0f0f0", 
  "contentBackgroundColor": "#fff", 
  "articleMaxWidth": "1080px", 
  "headingFontColor": "#000", 
  "weekTableFontHeight": 10, 
  "messageBorderColor": "#fff", 
  "inputBackground": "#fff", 
  "evenRowBackgroundColor": "#f0f0f0", 
  "twoColumnFormBackground": "#fff", 
  "background": "#fff", 
  "oddRowBackgroundColor": "#fff", 
  "twoColumnFormFontColor": "#000", 
  "memberActionsBoxBackground": "#f6f6f6", 
  "newsTitleBorderColor": "#ddd", 
  "fontSmallSize": "13px", 
  "messageFontColor": "#000", 
  "tabsBottomBorderSelectedWidth": "3px", 
  "fontBaseSize": "13px", 
  "listingHeaderBackgroundColor": "#ddd", 
  "highLightColor": "#ff9c00", 
  "calGridBorderColor": "#ccc", 
  "linkHoverColor": "#5af", 
  "topbar_background": "linear-gradient(to bottom, rgba(255,255,255,1) 0%, rgba(255,255,255,0.85) 100%)", 
  "outlineColor": "#ff9c00", 
  "headingFontFamily": "Helvetica, sans-serif", 
  "defaultShadow": "6px 6px 15px 0 rgba(0,0,0, 0.2)", 
  "articleBackground": "#fff"
}
;
