title:string=Color, font, logo and border defaults

backgroundColor:string=#fff
fontColor:string=#000
fontFamily:string=Arial, Helvetica, Geneva, Swiss, SunSans-Regular, sans-serif
fontBaseSize:string=90%
headingFontFamily:string=Arial, Helvetica, Geneva, Swiss, SunSans-Regular, sans-serif

linkColor:string=#369
linkHoverColor:string=#5af

fontSmallSize:string=90%


topbarBackgroundColor:string=#fff
breadcrumbsBackground:string=#fff

tabsBorderColor:string=#ddd
tabsBorderWidth:string=2px
tabsBottomBorderSelectedWidth:string=3px
tabsFontColor:string=#369
tabsBackgroundColor:string=#fff
selectedTabBackgroundColor:string=#fff

descriptionColor:string=#333

inputFontColor:string=#000

evenRowBackgroundColor:string=#f0f0f0
oddRowBackgroundColor:string=#fff
highLightColor:string=#ffa239

messageBackgroundColor:string=#fff
messageBorderColor:string=#fff

weekTableFontHeight:int=10
weekTableGridStep:int=10
todayBackgroundColor:string=#f0f0f0
calGridBorderColor:string=#ccc
calHalfGridBorderColor:string=#e5e5e5

contentBackgroundColor:string=#fff

configFontColor:string=#000
configBackgroundColor:string=#f0f0f0

portfolioSlideBackgroundColor:string=#f2f2f2

memberActionsBoxBackground:string=#f6f6f6
footerBackgroundColor:string=#f6f6f6
outlineColor:string=#ffa239
bylineBackgroundColor:string=#fff
messageFontColor:string=#000
listingHeaderBackgroundColor:string=#ddd
listingHeaderFontColor:string=#ddd
listingBarBorderColor:string=#ddd
newsTitleBorderColor:string=#ddd
boxesBorderColor:string=#ddd
specialLinkColor:string=#369
specialLinkHoverColor:string=#369
bulletColor:string=#369
boxeHeaderBackgroundColor:string=#fff

twoColumnFormFontColor:string=#000
twoColumnFormBackground:string=#ddd

borderRadius:int=7
