title:string=Color, font, logo and border defaults

background:string=#fff
backgroundColor:string=#fff
fontColor:string=#000
headingFontColor:string=#000
fontFamily:string=Helvetica, sans-serif
fontBaseSize:string=13px
fontMenuSize:string=16px
headingFontFamily:string=Helvetica, sans-serif

topbar_background:string=linear-gradient(to bottom, rgba(255,255,255,1) 0%, rgba(255,255,255,0.85) 100%)


linkColor:string=#369
linkHoverColor:string=#5af

fontSmallSize:string=13px


topbarBackgroundColor:string=#fff
breadcrumbsBackground:string=rgba(255,255,255,0.85)

tabsBorderColor:string=#ff9c00
tabsBorderWidth:string=2px
tabsBottomBorderSelectedWidth:string=3px
tabsFontColor:string=#369
tabsBackgroundColor:string=#fff
selectedTabBackgroundColor:string=#fff

descriptionColor:string=#333

inputFontColor:string=#000
inputBackground:string=#fff
inputSubmitColor:string=#000

evenRowBackgroundColor:string=#f0f0f0
oddRowBackgroundColor:string=#fff
highLightColor:string=#ff9c00

messageBackgroundColor:string=#fff
messageBorderColor:string=#fff

weekTableFontHeight:int=10
weekTableGridStep:int=10
todayBackgroundColor:string=#f0f0f0
calGridBorderColor:string=#ccc
calHalfGridBorderColor:string=#e5e5e5

contentBackgroundColor:string=#fff

configFontColor:string=#000
configBackgroundColor:string=#f0f0f0

portfolioSlideBackgroundColor:string=#f2f2f2

memberActionsBoxBackground:string=#f6f6f6
footerBackgroundColor:string=#000
outlineColor:string=#ff9c00
bylineBackgroundColor:string=#fff
messageFontColor:string=#000
listingHeaderBackgroundColor:string=#ddd
listingHeaderFontColor:string=#000
listingBarBorderColor:string=#ddd
newsTitleBorderColor:string=#ddd
boxesBorderColor:string=#ddd
sitePanelLinkColor:string=#a7d3ff
sitePanelLinkHoverColor:string=#f1f8ff
bulletColor:string=#369
boxeHeaderBackgroundColor:string=#ddd

twoColumnFormFontColor:string=#000
twoColumnFormBackground:string=#fff

borderRadius:int=7
articleBackground:string=#fff
articleWrapperBackground:string=transparent
articleMaxWidth:string=1080px
