selected_medium_image_background:string=unset
metadata_bar_background:string=#fff
image_toolbar_background:string=rgba(255,255,255, 0.85)
image_toolbar_border_color:string=silver
photographer_font_color:string=unset
title_font_color:string=unset
metadata_edit_label_color:string=#9da097
metadata_edit_panel_background:string=#3e3e3e
metadata_panel_border_sep_color:string=#484848
metadata_input_font_color:string=#d9d9d9
metadata_input_background:string=#3a3a3a
metadata_input_border_color:string=#3a3a3a
metadata_input_hover_background:string=#4c4c4c
metadata_input_focus_font_color:string=#000
metadata_input_focus_background:string=#fff
metadata_input_border_focus_color:string=#313131
portfolio_slide_background:string=#bfbfbf
portfolio_slide_hover_background:string=#e8e8e8
portfolio_slide_text_color:string=#000
slide_background:string=#fff
slide_hover_background:string=#fff
slide_selected_background:string=#727272
filmbar_background:string=#fff
filmbar_displayed_img_background:string=#bfbfbf
filmbar_hover_img_background:string=#e8e8e8