medium_image_background:string=#727272
metadata_bar_background:string=#555
photographer_font_color:string=#fff
title_font_color:string=#2b2b2b
metadata_edit_label_color:string=#9da097
metadata_edit_panel_background:string=#3e3e3e
metadata_panel_border_sep_color:string=#484848
metadata_input_font_color:string=#d9d9d9
metadata_input_background:string=#3a3a3a
metadata_input_border_color:string=#3a3a3a
metadata_input_hover_background:string=#4c4c4c
metadata_input_focus_font_color:string=#000
metadata_input_focus_background:string=#fff
metadata_input_border_focus_color:string=#313131
portfolio_slide_background:string=#1b1b1b
portfolio_slide_hover_background:string=#2b2b2b
slide_background:string=#555
slide_hover_background:string=#606060
slide_selected_background:string=#727272
